load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fortune",
    srcs = ["fortune.go"],
    importpath = "github.com/tonghia/unitary/go-tutorial/stage2/fortune",
    visibility = ["//visibility:public"],
)
